{% set name = "libleidenalg" %}
{% set version = "0.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/vtraag/libleidenalg/archive/refs/tags/{{ version }}.tar.gz
  sha256: e3a766449e0bee137e4a8b2c5506c4bdc00cec246ccf1c93d8e86bbd253bc5c4
  patches:
    - 001-cmake-fix-link-libraries.patch

build:
  number: 1
  run_exports:
    - {{ pin_subpackage("libleidenalg", max_pin="x.x") }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - igraph >=0.10,<0.11

test:
  files:
    - test.cpp
  requires:
    - {{ compiler('cxx') }}

about:
  home: https://github.com/vtraag/libleidenalg
  summary: Leiden is a general algorithm for methods of community detection in large networks.
  description: |
    This package implements the Leiden algorithm in C++. It relies on igraph for
    it to function. Besides the relative flexibility of the implementation, it
    also scales well, and can be run on graphs of millions of nodes (as long as
    they can fit in memory). The core class is the Optimiser class which is able
    to optimize a variety of quality functions using the Leiden algorithm.
  license: GPL-3.0-or-later
  license_family: GPL
  license_file: LICENSE
  dev_url: https://github.com/vtraag/libleidenalg

extra:
  recipe-maintainers:
    - vtraag
